### ISSUE TITLE
EVM compatible chains support?

### ISSUE THREAD

**Issue by tomatt131** [openrelayxyz/log-flume#22]
Hello, is it possible to run flume for chains other than Ethereum but that are EVM based? e.g. Binance Smart Chain, Avax etc.
On river cloud I've seen that its possible to switch between various testnet chains so would it should also be possible to configure Flume to an EVM compatible chain right?

**Comment by AusIV** [comment]
Right now the set of chains supported by Flume is hard coded, but we'd certainly accept PRs to get it to support other chains (mainly we need chainids and a few pieces of information in order to correctly count issuance per block).

The other caveat is  that some chains have additional block headers related to their consensus mechanisms, and currently we don't have a way to support that.
